export type AlbumImage = {
  src: string;
  alt: string;
};

export type Album = {
  slug: string;
  title: string;
  event: string;
  date: string;
  location: string;
  excerpt: string;
  cover: AlbumImage;
  images: AlbumImage[];
};

function ph(seed: string, w: number, h: number) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export const albums: Album[] = [
  {
    slug: "rs-fahim-manjia",
    title: "RS Fahim & Manjia",
    event: "Wedding",
    date: "2024-02-14",
    location: "Dhaka",
    excerpt: "A wedding covered end to end one of our most-followed galleries.",
    cover: { src: "/rsfahim.webp", alt: "RS Fahim and Manjia, wedding cover photo" },
    images: [
      { src: "/rsfahim.webp", alt: "RS Fahim and Manjia, wedding portrait" },
      { src: "/rsfahim1.webp", alt: "RS Fahim and Manjia, ceremony moment" },
      { src: "/rsfahim2.webp", alt: "RS Fahim and Manjia, candid portrait" },
      { src: "/rsfahim3.webp", alt: "RS Fahim and Manjia, detail shot" },
      { src: "https://i.ibb.co.com/KzsSQtTm/rsfahim4.webp", alt: "RS Fahim and Manjia, family moment" },
      { src: "https://i.ibb.co.com/JW6RtJL7/rsfahim5.webp", alt: "RS Fahim and Manjia, reception" },
      { src: "https://i.ibb.co.com/5WsJQS2R/rsfahim6.webp", alt: "RS Fahim and Manjia, candid moment" },
      { src: "https://i.ibb.co.com/SXVmJRdM/rsfahim7.webp", alt: "RS Fahim and Manjia, portrait" },
      { src: "https://i.ibb.co.com/YTkKBgBd/rsfahim8.webp", alt: "RS Fahim and Manjia, guests" },
      { src: "https://i.ibb.co.com/mCRrdRZz/rsfahim9.webp", alt: "RS Fahim and Manjia, closing moment" },
      { src: "https://i.ibb.co.com/kgRL92VS/rsfahim10.webp", alt: "RS Fahim and Manjia, final portrait" },
      { src: "https://i.ibb.co.com/BVWHSts4/rsfahim11.webp", alt: "RS Fahim and Manjia, wedding portrait" },
      { src: "https://i.ibb.co.com/qMjDXgdN/rsfahim13.webp", alt: "RS Fahim and Manjia, guests" },
      { src: "https://i.ibb.co.com/6cHwnpQT/rsfahim14.webp", alt: "RS Fahim and Manjia, closing moment" },
      { src: "https://i.ibb.co.com/8gJmdzXv/rsfahim15.webp", alt: "RS Fahim and Manjia, final portrait" },
      { src: "https://i.ibb.co.com/Y7QRnqpd/rsfahim16.webp", alt: "RS Fahim and Manjia, wedding portrait" },
    ],
  },
  {
    slug: "jabin-emran",
    title: "Jabin & Emran",
    event: "Wedding",
    date: "2026-05-20",
    location: "Dhaka",
    excerpt: "",
    cover: { src: "/jebin.webp", alt: "Jabin and Emran, wedding cover photo" },
    images: [
      { src: "/jebin.webp", alt: "Jabin and Emran, wedding portrait" },
      { src: "/jebin1.webp", alt: "Jabin and Emran, ceremony moment" },
      { src: "/jebin2.webp", alt: "Jabin and Emran, candid portrait" },
      { src: "/jebin3.webp", alt: "Jabin and Emran, detail shot" },
      { src: "/jebin4.webp", alt: "Jabin and Emran, family moment" },
      { src: "/jebin5.webp", alt: "Jabin and Emran, reception" },
      { src: "/jebin6.webp", alt: "Jabin and Emran, candid moment" },
      { src: "/jebin7.webp", alt: "Jabin and Emran, portrait" },
      { src: "/jebin8.webp", alt: "Jabin and Emran, closing moment" },
      { src: "/jebin9.webp", alt: "Jabin and Emran, final portrait" },
      { src: "/jebin10.webp", alt: "Jabin and Emran, detail shot" },
      { src: "/jebin11.webp", alt: "Jabin and Emran, family moment" },
    ],
  },
  {
    slug: "raisa-minhaj",
    title: "Raisa & Minhaj",
    event: "Akhd",
    date: "2025-11-08",
    location: "Dhaka",
    excerpt: "An intimate akhd ceremony, captured in timeless frames.",
    cover: { src: "/raisa.webp", alt: "Raisa and Minhaj, akhd cover photo" },
    images: [
      { src: "/raisa.webp", alt: "Raisa and Minhaj, portrait" },
      { src: "https://i.ibb.co.com/zdNZVqX/raisa1.jpg", alt: "Raisa and Minhaj, ceremony moment" },
      { src: "https://i.ibb.co.com/NnKKnQtM/raisa2.jpg", alt: "Raisa and Minhaj, candid portrait" },
      { src: "https://i.ibb.co.com/k2Fp8Qkt/raisa3.jpg", alt: "Raisa and Minhaj, detail shot" },
      { src: "https://i.ibb.co.com/h19VqT7G/raisa5.jpg", alt: "Raisa and Minhaj, family moment" },
      { src: "https://i.ibb.co.com/nqwVtFY6/raisa11.jpg", alt: "Raisa and Minhaj, reception" },
      { src: "https://i.ibb.co.com/N2WBT44y/raisa10.jpg", alt: "Raisa and Minhaj, portrait" },
      { src: "https://i.ibb.co.com/vCj3rnsk/raisa9.jpg", alt: "Raisa and Minhaj, ceremony moment" },
      { src: "https://i.ibb.co.com/0zBhRst/raisa8.jpg", alt: "Raisa and Minhaj, candid portrait" },
      { src: "https://i.ibb.co.com/5WmCn9b4/raisa7.jpg", alt: "Raisa and Minhaj, detail shot" },
      { src: "https://i.ibb.co.com/5W17BzN0/raisa6.jpg", alt: "Raisa and Minhaj, family moment" },
      { src: "https://i.ibb.co.com/wr7BY2TW/raisa4.jpg", alt: "Raisa and Minhaj, reception" },
    ],
  },
  {
    slug: "50th",
    title: "50th anniversary",
    event: "Anniversary",
    date: "2026-02-21",
    location: "Dhaka",
    excerpt: "A golden anniversary celebration, with a family portrait session.",
    cover: { src: "/50th.webp", alt: "Sayma, holud cover photo" },
    images: [
      { src: "/50th.webp", alt: "Sayma, holud portrait" },
      { src: "/50th1.webp", alt: "Sayma, ceremony moment" },
      { src: "/50th2.webp", alt: "Sayma, candid portrait" },
      { src: "/50th3.webp", alt: "Sayma, detail shot" },
      { src: "/50th4.webp", alt: "Sayma, family moment" },
      { src: "/50th5.webp", alt: "Sayma, reception" },
      { src: "/50th6.webp", alt: "Sayma, candid moment" },
      { src: "/50th7.webp", alt: "Sayma, portrait" },
      { src: "/50th8.webp", alt: "Sayma, family moment" },
      { src: "/50th9.webp", alt: "Sayma, reception" },
      { src: "/50th10.webp", alt: "Sayma, candid moment" },
      { src: "/50th11.webp", alt: "Sayma, portrait" },
      { src: "/50th14.webp", alt: "Sayma, family moment" },
      { src: "/50th12.webp", alt: "Sayma, reception" },
      { src: "/50th16.webp", alt: "Sayma, candid moment" },
      { src: "/50th13.webp", alt: "Sayma, portrait" },
    ],
  },
  {
    slug: "juthy-sharan",
    title: "Juthy & Sharan",
    event: "Nikah",
    date: "2024-08-09",
    location: "Dhaka",
    excerpt: "An intimate nikah ceremony, shot in soft light.",
    cover: { src: "/juthy.webp", alt: "Juthy and Sharan, wedding cover photo" },
    images: [
      { src: "/juthy.webp", alt: "Juthy and Sharan, wedding portrait" },
      { src: "/juthy1.webp", alt: "Juthy and Sharan, ceremony moment" },
      { src: "/juthy2.webp", alt: "Juthy and Sharan, candid portrait" },
      { src: "/juthy3.webp", alt: "Juthy and Sharan, detail shot" },
      { src: "/juthy4.webp", alt: "Juthy and Sharan, family moment" },
      { src: "/juthy5.webp", alt: "Juthy and Sharan, reception" },
      { src: "/juthy6.webp", alt: "Juthy and Sharan, candid moment" },
      { src: "/juthy7.webp", alt: "Juthy and Sharan, portrait" },
      { src: "/juthy8.webp", alt: "Juthy and Sharan, guests" },
      { src: "/juthy9.webp", alt: "Juthy and Sharan, closing moment" },
      { src: "/juthy10.webp", alt: "Juthy and Sharan, final portrait" },
      { src: "/juthy11.webp", alt: "Juthy and Sharan, wedding portrait" },
      { src: "/juthy12.webp", alt: "Juthy and Sharan, wedding portrait" },
    ],
  },
  {
    slug: "rajan-mourita",
    title: "Rajan & Mourita",
    event: "Pre-wedding",
    date: "2025-10-09",
    location: "Dhaka",
    excerpt: "A destination-style resort wedding with lake-side portraits at sunset.",
    cover: { src: "/rajan.webp", alt: "Rajan and Mourita, wedding cover photo" },
    images: [
      { src: "/rajan.webp", alt: "Rajan and Mourita, wedding portrait" },
      { src: "https://i.ibb.co.com/0jzCGPDm/rajan1.webp", alt: "Rajan and Mourita, ceremony moment" },
      { src: "https://i.ibb.co.com/PZ0FHg0n/rajan2.webp", alt: "Rajan and Mourita, candid portrait" },
      { src: "https://i.ibb.co.com/MDgD5v5D/rajan3.webp", alt: "Rajan and Mourita, detail shot" },
      { src: "https://i.ibb.co.com/7xqVKRcG/rajan4.webp", alt: "Rajan and Mourita, family moment" },
      { src: "https://i.ibb.co.com/jZH5Fds7/rajan5.webp", alt: "Rajan and Mourita, reception" },
      { src: "https://i.ibb.co.com/VWPSWzjx/rajan6.webp", alt: "Rajan and Mourita, candid moment" },
      { src: "https://i.ibb.co.com/jvbCJ5MD/rajan7.webp", alt: "Rajan and Mourita, portrait" },
      { src: "https://i.ibb.co.com/9HGS2NHz/rajan8.webp", alt: "Rajan and Mourita, guests" },
      { src: "https://i.ibb.co.com/TBhNN0qY/rajan9.webp", alt: "Rajan and Mourita, closing moment" },
      { src: "https://i.ibb.co.com/84b4vTQX/rajan10.webp", alt: "Rajan and Mourita, final portrait" },
      { src: "https://i.ibb.co.com/zWwX3TxH/rajan11.webp", alt: "Rajan and Mourita, wedding portrait" },
      { src: "https://i.ibb.co.com/s9nsGFhK/rajan12.webp", alt: "Rajan and Mourita, candid portrait" },
      { src: "https://i.ibb.co.com/nN3bkHgc/rajan13.webp", alt: "Rajan and Mourita, detail shot" },
      { src: "https://i.ibb.co.com/RGzhRLC4/rajan14.webp", alt: "Rajan and Mourita, family moment" },
      { src: "https://i.ibb.co.com/HfqH984s/rajan15.webp", alt: "Rajan and Mourita, reception" },
      { src: "https://i.ibb.co.com/wGXrvL9/rajan16.webp", alt: "Rajan and Mourita, candid moment" },
      { src: "https://i.ibb.co.com/C4dq1Bf/rajan17.webp", alt: "Rajan and Mourita, portrait" },
      { src: "https://i.ibb.co.com/zTt2kHgw/rajan18.webp", alt: "Rajan and Mourita, guests" },
      { src: "https://i.ibb.co.com/Q3r2cDFv/rajan19.webp", alt: "Rajan and Mourita, closing moment" },
      { src: "https://i.ibb.co.com/HfKhWWF2/rajan20.webp", alt: "Rajan and Mourita, final portrait" },
      { src: "https://i.ibb.co.com/8L2JsNYb/rajan21.webp", alt: "Rajan and Mourita, reception" },
      { src: "https://i.ibb.co.com/1G5hK1yt/rajan22.webp", alt: "Rajan and Mourita, portrait" },
      { src: "https://i.ibb.co.com/C3RjJtZ9/rajan23.webp", alt: "Rajan and Mourita, guests" },
      { src: "https://i.ibb.co.com/bjZ4ThYX/rajan24.webp", alt: "Rajan and Mourita, closing moment" },
    ],
  },
  {
    slug: "oishi-sabbir",
    title: "Oishi & Sabbir",
    event: "Photoshoot cox-bazar",
    date: "2025-12-14",
    location: "Dhaka",
    excerpt: "",
    cover: { src: "/sabbir.webp", alt: "Oishi and Sabbir, wedding cover photo" },
    images: [
      { src: "/sabbir.webp", alt: "Oishi and Sabbir, wedding portrait" },
      { src: "https://i.ibb.co.com/q3w6Ggwt/sabbir1.webp", alt: "Oishi and Sabbir, ceremony moment" },
      { src: "https://i.ibb.co.com/5XbFFkRG/sabbir2.webp", alt: "Oishi and Sabbir, candid portrait" },
      { src: "https://i.ibb.co.com/60MGfGrt/sabbir3.webp", alt: "Oishi and Sabbir, detail shot" },
      { src: "https://i.ibb.co.com/gZHv9GNQ/sabbir4.webp", alt: "Oishi and Sabbir, family moment" },
      { src: "https://i.ibb.co.com/s9g2LHY3/sabbir5.webp", alt: "Oishi and Sabbir, reception" },
      { src: "https://i.ibb.co.com/tTcKhPwv/sabbir6.webp", alt: "Oishi and Sabbir, candid moment" },
      { src: "https://i.ibb.co.com/k2cD9HwZ/sabbir7.webp", alt: "Oishi and Sabbir, portrait" },
      { src: "https://i.ibb.co.com/MxsH7hZ8/sabbir8.webp", alt: "Oishi and Sabbir, wedding portrait" },
      { src: "https://i.ibb.co.com/QjnxRNgj/sabbir24.webp", alt: "Oishi and Sabbir, ceremony moment" },
      { src: "https://i.ibb.co.com/cz85gDS/sabbir19.webp", alt: "Oishi and Sabbir, candid portrait" },
      { src: "https://i.ibb.co.com/pvZsgy4N/sabbir9.webp", alt: "Oishi and Sabbir, detail shot" },
      { src: "https://i.ibb.co.com/M5k3tBQD/sabbir10.webp", alt: "Oishi and Sabbir, family moment" },
      { src: "https://i.ibb.co.com/9HMHDr1v/sabbir16.webp", alt: "Oishi and Sabbir, reception" },
    ],
  },
  {
    slug: "lamha-fuad",
    title: "Lamha & Fuad",
    event: "",
    date: "2025-11-08",
    location: "Dhaka",
    excerpt: "",
    cover: { src: "/fuad.webp", alt: "Lamha and Fuad cover photo" },
    images: [
      { src: "/fuad.webp", alt: "Lamha and Fuad portrait" },
      { src: "/fuad1.webp", alt: "Lamha and Fuad, ceremony moment" },
      { src: "/fuad2.webp", alt: "Lamha and Fuad, candid portrait" },
      { src: "/fuad3.webp", alt: "Lamha and Fuad, detail shot" },
      { src: "/fuad4.webp", alt: "Lamha and Fuad, family moment" },
      { src: "/fuad5.webp", alt: "Lamha and Fuad, reception" },
      { src: "/fuad6.webp", alt: "Lamha and Fuad portrait" },
      { src: "/fuad7.webp", alt: "Lamha and Fuad, ceremony moment" },
      { src: "/fuad8.webp", alt: "Lamha and Fuad, candid portrait" },
    ],
  },
  {
    slug: "fazrin",
    title: "Fazrin",
    event: "Birthday",
    date: "2025-11-08",
    location: "Dhaka",
    excerpt: "",
    cover: { src: "/fazrin.webp", alt: "Fazrin, birthday cover photo" },
    images: [
      { src: "/fazrin.webp", alt: "Fazrin, birthday portrait" },
      { src: "/fazrin1.webp", alt: "Fazrin, ceremony moment" },
      { src: "/fazrin2.webp", alt: "Fazrin, candid portrait" },
      { src: "/fazrin3.webp", alt: "Fazrin, detail shot" },
      { src: "/fazrin4.webp", alt: "Fazrin, family moment" },
      { src: "/fazrin5.webp", alt: "Fazrin, reception" },
      { src: "/fazrin6.webp", alt: "Fazrin, birthday portrait" },
      { src: "/fazrin7.webp", alt: "Fazrin, ceremony moment" },
      { src: "/fazrin8.webp", alt: "Fazrin, candid portrait" },
      { src: "/fazrin9.webp", alt: "Fazrin, detail shot" },
      { src: "/fazrin10.webp", alt: "Fazrin, family moment" },
      { src: "/fazrin11.webp", alt: "Fazrin, reception" },
      { src: "/fazrin12.webp", alt: "Fazrin, birthday moment" },
    ],
  },
];

export function getAlbumBySlug(slug: string) {
  return albums.find((a) => a.slug === slug);
}